
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    username: 
    password: 
    url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  auto-deployment-enabled: false
  
